In [2]:
import mygene
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

# Download infos

In [6]:
mg = mygene.MyGeneInfo()

In [7]:
mg.getgenes(['ENSG00000242268'], 'name,symbol,refseq.rna,type_of_gene')

querying 1-1...done.

[{u'_id': u'100507661',
  u'_score': 19.5394,
  u'name': u'long intergenic non-protein coding RNA 2082',
  u'query': u'ENSG00000242268',
  u'refseq': {u'rna': u'NR_109989.1'},
  u'symbol': u'LINC02082',
  u'type_of_gene': u'ncRNA'}]

In [8]:
df = pd.read_csv("genes.txt", header=None)
df.head()

                    0
0   ENSG00000242268.2
1   ENSG00000270112.3
2  ENSG00000167578.15
3   ENSG00000273842.1
4   ENSG00000078237.5

In [ ]:
query = mg.getgenes([g[:15] for g in df[0].values], 'name,symbol,refseq.rna, type_of_gene')

In [ ]:
query[0]

In [ ]:
types = []
for t in query:
    try:
        types.append(t['type_of_gene'])
    except:
        types.append('unknown')

## count types

In [ ]:
utype, count = np.unique(np.array(types), return_counts=True)

In [ ]:
fig = plt.figure(figsize=(10,5))
plt.bar(utype, count, color='blue')
plt.ylabel("# genes", fontsize=16)
plt.show()
fig.savefig("genes_distr.pdf")

In [70]:
np.sum(count[:-1])

24910

In [ ]:
protein_codings = []
for q in query:
    try:
        if(q['type_of_gene']!='unknown'):
            protein_codings.append(q['query'])
    except:
        pass

In [ ]:
#df_pc = pd.DataFrame(data=protein_codings)
#df_pc.head()
#df_pc.to_csv("genes_pc.txt", header=None, index=None)

In [36]:
protein_codings

array(['ENSG00000242268', 'ENSG00000167578', 'ENSG00000078237', ...,
       'ENSG00000231119', 'ENSG00000123685', 'ENSG00000181518'],
      dtype=object)

# Load infos

In [11]:
df_pc = pd.read_csv("genes_pc.txt", header=None)

In [16]:
protein_codings = df_pc[0].values

In [3]:
df_main = pd.read_csv("mainTable.csv")
genes = np.array([gene[:15] for gene in df_main.loc[:,'gene'].values])
df_main['gene'] = genes
df_main.head()

,gene,821e42cc-d1b9-48e1-959d-9df561c4aeb5.F,5d7766c6-e42f-4f85-9065-d8bcc54d7db9.F,f1f609a2-4fd6-48fc-8a29-3bc39c6ff178.F,29d09b58-3cc2-47c0-b78e-18743eed2c2f.F,f9153720-86f1-4d70-b2a9-7b88dd365514.F,597e0bf5-b228-432f-b469-9498bb812f98.F,f79772b6-251a-447c-a1dc-e77521d98c15.F,20e20086-f76a-48f1-a1a8-c2de77a092b0.F,0ca8f6dd-6ffc-416c-8f06-5dee152618a9.F,...,21e82bf2-237f-4f8f-86d0-aaf2ea5c4729.F,7f5a924a-ddf3-45ff-be1f-5b5909305f46.F,d5c8759b-0dc1-4057-b9df-c9aa4a6b2a04.F,d3f73c0f-d518-4e91-b038-a4360495ee27.F,4869e2a4-f182-41f1-8aed-52b5dd3b5c00.F,d8b37f77-500a-4c1e-b344-41f4e0c6fea6.F,46551ef6-d1de-43c3-8ea5-5ade8a5bffd7.F,1a587b92-0a11-47f0-83c2-77a2b6de1088.F,9c77be54-d58e-4dec-8894-acb71a12cac5.F,2556ce90-db5f-4beb-897a-db3cf556e054.F
0,ENSG00000242268,0.000000,0.000000,1.427633,0.000000,0.061914,0.026550,0.055186,1.346753,0.000000,...,0.023556,0.000000,0.000000,0.286641,0.513100,0.000000,0.027827,0.000000,0.000000,0.000000
1,ENSG00000270112,0.000000,0.006083,0.177454,0.000000,0.008591,0.011052,0.033181,0.000000,0.000000,...,0.000000,0.010471,0.010444,0.015909,0.000000,0.009306,0.003861,0.031637,0.000000,0.016449
2,ENSG00000167578,4.335807,4.711715,5.851848,3.270882,3.651170,4.740114,2.531203,3.267413,1.359582,...,3.538693,2.163905,3.348341,2.222798,5.219926,5.666720,2.509192,1.182190,3.463509,3.816159
3,ENSG00000273842,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,ENSG00000078237,6.277226,1.997385,7.446510,2.287782,3.679019,1.696093,2.121344,6.365669,4.144660,...,5.455092,4.750105,5.774992,2.558247,2.870966,4.079897,2.699238,6.278986,6.234426,5.366732

In [33]:
df_main_pc = pd.DataFrame(columns=df_main.columns)
df_main_pc.to_csv("mainTable_pc.csv", index = False)

In [34]:
for i, gene in enumerate(protein_codings):
    df_main.loc[df_main['gene']==gene].to_csv("mainTable_pc.csv", mode='a', header=None, index=False)
    if(i%100==0):
        print("elapsed %d"%i)

elapsed 0
elapsed 100
elapsed 200
elapsed 300
elapsed 400
elapsed 500
elapsed 600
elapsed 700
elapsed 800
elapsed 900
elapsed 1000
elapsed 1100
elapsed 1200
elapsed 1300
elapsed 1400
elapsed 1500
elapsed 1600
elapsed 1700
elapsed 1800
elapsed 1900
elapsed 2000
elapsed 2100
elapsed 2200
elapsed 2300
elapsed 2400
elapsed 2500
elapsed 2600
elapsed 2700
elapsed 2800
elapsed 2900
elapsed 3000
elapsed 3100
elapsed 3200
elapsed 3300
elapsed 3400
elapsed 3500
elapsed 3600
elapsed 3700
elapsed 3800
elapsed 3900
elapsed 4000
elapsed 4100
elapsed 4200
elapsed 4300
elapsed 4400
elapsed 4500
elapsed 4600
elapsed 4700
elapsed 4800
elapsed 4900
elapsed 5000
elapsed 5100
elapsed 5200
elapsed 5300
elapsed 5400
elapsed 5500
elapsed 5600
elapsed 5700
elapsed 5800
elapsed 5900
elapsed 6000
elapsed 6100
elapsed 6200
elapsed 6300
elapsed 6400
elapsed 6500
elapsed 6600
elapsed 6700
elapsed 6800
elapsed 6900
elapsed 7000
elapsed 7100
elapsed 7200
elapsed 7300
elapsed 7400
elapsed 7500
elapsed 7600
elapsed 7700
elapsed 7800
elapsed 7900
elapsed 8000
elapsed 8100
elapsed 8200
elapsed 8300
elapsed 8400
elapsed 8500
elapsed 8600
elapsed 8700
elapsed 8800
elapsed 8900
elapsed 9000
elapsed 9100
elapsed 9200
elapsed 9300
elapsed 9400
elapsed 9500
elapsed 9600
elapsed 9700
elapsed 9800
elapsed 9900
elapsed 10000
elapsed 10100
elapsed 10200
elapsed 10300
elapsed 10400
elapsed 10500
elapsed 10600
elapsed 10700
elapsed 10800
elapsed 10900
elapsed 11000
elapsed 11100
elapsed 11200
elapsed 11300
elapsed 11400
elapsed 11500
elapsed 11600
elapsed 11700
elapsed 11800
elapsed 11900
elapsed 12000
elapsed 12100
elapsed 12200
elapsed 12300
elapsed 12400
elapsed 12500
elapsed 12600
elapsed 12700
elapsed 12800
elapsed 12900
elapsed 13000
elapsed 13100
elapsed 13200
elapsed 13300
elapsed 13400
elapsed 13500
elapsed 13600
elapsed 13700
elapsed 13800
elapsed 13900
elapsed 14000
elapsed 14100
elapsed 14200
elapsed 14300
elapsed 14400
elapsed 14500
elapsed 14600
elapsed 14700
elapsed 14800
elapsed 14900
elapsed 15000
elapsed 15100
elapsed 15200
elapsed 15300
elapsed 15400
elapsed 15500
elapsed 15600
elapsed 15700
elapsed 15800
elapsed 15900
elapsed 16000
elapsed 16100
elapsed 16200
elapsed 16300
elapsed 16400
elapsed 16500
elapsed 16600
elapsed 16700
elapsed 16800
elapsed 16900
elapsed 17000
elapsed 17100
elapsed 17200
elapsed 17300
elapsed 17400
elapsed 17500
elapsed 17600
elapsed 17700
elapsed 17800
elapsed 17900
elapsed 18000
elapsed 18100
elapsed 18200
elapsed 18300
elapsed 18400
elapsed 18500
elapsed 18600
elapsed 18700
elapsed 18800
elapsed 18900
elapsed 19000
elapsed 19100
elapsed 19200
elapsed 19300
elapsed 19400
elapsed 19500
elapsed 19600
elapsed 19700
elapsed 19800
elapsed 19900
elapsed 20000
elapsed 20100
elapsed 20200
elapsed 20300
elapsed 20400
elapsed 20500
elapsed 20600
elapsed 20700
elapsed 20800
elapsed 20900
elapsed 21000
elapsed 21100
elapsed 21200
elapsed 21300
elapsed 21400
elapsed 21500
elapsed 21600
elapsed 21700
elapsed 21800
elapsed 21900
elapsed 22000
elapsed 22100
elapsed 22200
elapsed 22300
elapsed 22400
elapsed 22500
elapsed 22600
elapsed 22700
elapsed 22800
elapsed 22900
elapsed 23000
elapsed 23100
elapsed 23200
elapsed 23300
elapsed 23400
elapsed 23500
elapsed 23600
elapsed 23700
elapsed 23800
elapsed 23900
elapsed 24000
elapsed 24100
elapsed 24200
elapsed 24300
elapsed 24400
elapsed 24500
elapsed 24600
elapsed 24700
elapsed 24800
elapsed 24900